[tool.poetry]
name = "pytse-client"
version = "0.3.1"

description = "tehran stock exchange(TSE) client in python"
authors = ["glyphack <sh.hooshyari@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = "*"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
